"""High-throughput conversion of model-output CSVs into GeoJSON overlays."""

# geojson_vectorized_serial.py
from __future__ import annotations

import json
import uuid
from colorsys import hsv_to_rgb

# from shapely.geometry import Polygon, MultiPolygon  # (imported only for typing)
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
from typing import Dict
from typing import List
from typing import Optional
from typing import Tuple
from typing import Union

import geopandas as gpd
import h5py
import logging
import numpy as np
import orjson
import pandas as pd
from shapely import from_wkt  # shapely >= 2.0
from tqdm.auto import tqdm
import threading as _threading
from .cli.export import _to_local_path  # local URI-vs-Path resolver

logger = logging.getLogger(__name__)
_write_csv_to_h5_lock = _threading.Lock()
# `Lock` is referenced by the legacy (dead) `_build_geojson_dict_from_h5`
# below; keep an alias so it cannot NameError if anything ever calls it.
Lock = _write_csv_to_h5_lock

from .cancel import cancellable_as_completed
from .uri_path import URIPath

PathLike = Union[Path, URIPath]

# Columns that carry geometry/identity — excluded from per-cell measurements.
_GEOM_COLS = frozenset(
    {
        "minx",
        "miny",
        "width",
        "height",
        "center_x",
        "center_y",
        "polygon_wkt",
    }
)

# from .num_worker_optimizer import pick_workers_safe, throttle_when_busy

# ---- fast JSON encoder ----


def _dumps(obj: dict) -> bytes:
    """Serialize a GeoJSON dictionary using the fast `orjson` backend."""
    return orjson.dumps(obj, option=orjson.OPT_SERIALIZE_NUMPY)


# --------------------------
# Helpers
# --------------------------
def _make_distinct_colors(
    n: int,
    s: float = 0.70,
    v: float = 0.90,
    shuffle: bool = True,
    seed: Optional[int] = None,
):
    """Return `n` well-spaced HSV-derived colors for class visualization."""
    if n <= 0:
        raise ValueError("n must be > 0")
    hues = [i / n for i in range(n)]
    if shuffle and n > 2:
        order, L, R = [], 0, n - 1
        while L <= R:
            order.append(L)
            if L != R:
                order.append(R)
            L += 1
            R -= 1
        hues = [hues[i] for i in order]
    if seed is not None:
        import random

        random.seed(seed)

    out = []
    for h in hues:
        r, g, b = hsv_to_rgb(h, s, v)
        R, G, B = (int(round(r * 255)), int(round(g * 255)), int(round(b * 255)))
        out.append(
            {"hex": f"#{R:02X}{G:02X}{B:02X}", "rgb": (R, G, B), "hsv": (h, s, v)}
        )
    return out


# --------------------------
# BOX path (vectorized)
# --------------------------
def _dataframe_to_geojson_box_fast(
    df: pd.DataFrame,
    prob_cols: List[str],
    overlap: float,
    *,
    prefix: str = "prob",
    object_type: str = "tile",
    set_classification: bool = False,
    color_list: Optional[List[dict]] = None,
    class_names: Optional[List[str]] = None,
) -> dict:
    """Vectorize CSV tile boxes into a GeoJSON FeatureCollection."""
    # Keep only valid rows for probs
    df = df.dropna(subset=[c for c in prob_cols if c.startswith(prefix)])

    # Pull numeric columns to arrays (no per-row pandas calls)
    xywh = df[["minx", "miny", "width", "height"]].to_numpy(dtype=np.int64, copy=False)
    minx, miny, w, h = xywh.T

    # Vectorized patch math
    pw = np.rint(w * (1.0 - overlap)).astype(np.int64)
    ph = np.rint(h * (1.0 - overlap)).astype(np.int64)
    pmx = np.rint((w - pw) * 0.5).astype(np.int64)
    pmy = np.rint((h - ph) * 0.5).astype(np.int64)

    minx2 = minx + pmx
    miny2 = miny + pmy
    maxx2 = minx2 + pw
    maxy2 = miny2 + ph

    # Closed ring coordinates (N, 5, 2)
    coords = np.stack(
        [
            np.stack([maxx2, miny2], axis=1),
            np.stack([maxx2, maxy2], axis=1),
            np.stack([minx2, maxy2], axis=1),
            np.stack([minx2, miny2], axis=1),
            np.stack([maxx2, miny2], axis=1),
        ],
        axis=1,
    )

    # Probs as matrix, argmax vectorized (classification only)
    probs = df[prob_cols].to_numpy(dtype=np.float32, copy=False)
    arg = probs.argmax(axis=1)

    if color_list is None:
        color_list = _make_distinct_colors(len(prob_cols))

    if class_names is None:
        class_names = [
            f"{prefix}_{c[len(prefix) + 1:]}"
            if c.startswith(f"{prefix}_")
            else f"{prefix}_{c}"
            for c in prob_cols
        ]

    # All numeric non-geometry columns → measurements (includes prob_*, hplot_*, ncomp_*, etc.)
    # Exclude internal __oh_*__ one-hot columns generated by the label_col path.
    measure_cols = [
        c
        for c in df.columns
        if c not in _GEOM_COLS
        and not c.startswith("__oh_")
        and pd.api.types.is_numeric_dtype(df[c])
    ]
    meas_arr = df[measure_cols].to_numpy(dtype=np.float64, copy=False)

    # Build features in one tight Python loop (no pandas ops inside)
    features = []
    for i in range(len(df)):
        measurements = {
            c: (None if np.isnan(v) else float(v))
            for c, v in zip(measure_cols, meas_arr[i], strict=False)
        }
        feat = {
            "type": "Feature",
            "id": str(uuid.uuid4()),
            # "geometry": {"type": "Polygon", "coordinates": [list(map(tuple, coords[i]))]},
            "geometry": {"type": "Polygon", "coordinates": [coords[i].tolist()]},
            "properties": {
                "isLocked": True,
                "measurements": measurements,
                "objectType": object_type,
            },
        }
        if set_classification:
            ci = int(arg[i])
            feat["properties"]["classification"] = {
                "name": class_names[ci],
                "color": list(color_list[ci]["rgb"]),
            }
        features.append(feat)

    return {"type": "FeatureCollection", "features": features}


# --------------------------
# POLYGON/WKT path (GeoPandas + Shapely vectorized)
# --------------------------
def _dataframe_to_geojson_polygon_fast(
    df: pd.DataFrame,
    prob_cols: List[str],
    *,
    prefix: str = "prob",
    object_type: str = "tile",
    set_classification: bool = False,
    color_list: Optional[List[dict]] = None,
    class_names: Optional[List[str]] = None,
    crs: Optional[str] = None,
) -> dict:
    """Convert Shapely-backed polygon annotations into GeoJSON quickly."""
    # Vectorized WKT → geometry (Shapely 2 ufunc)
    geom = from_wkt(df["polygon_wkt"])

    # Properties (copy needed bits; avoid huge extra columns)
    props = df.drop(columns=["polygon_wkt"]).copy()

    # Argmax over probs (vectorized)
    probs = props[prob_cols].to_numpy(dtype=np.float32, copy=False)
    idx = probs.argmax(axis=1)

    if class_names is None:
        class_names = [
            f"{prefix}_{c[len(prefix) + 1:]}"
            if c.startswith(f"{prefix}_")
            else f"{prefix}_{c}"
            for c in prob_cols
        ]

    if color_list is None:
        color_list = _make_distinct_colors(len(prob_cols))

    # All numeric non-geometry columns → measurements (includes prob_*, hplot_*, ncomp_*, etc.)
    # Exclude internal __oh_*__ one-hot columns generated by the label_col path.
    measure_cols = [
        c
        for c in props.columns
        if c not in _GEOM_COLS
        and not c.startswith("__oh_")
        and pd.api.types.is_numeric_dtype(props[c])
    ]
    meas_arr = props[measure_cols].to_numpy(dtype=np.float64, copy=False)

    # Pack your custom fields
    props["objectType"] = object_type
    if set_classification:
        props["classification"] = [
            {"name": class_names[i], "color": list(color_list[i]["rgb"])} for i in idx
        ]
    props["measurements"] = [
        {
            c: (None if np.isnan(v) else float(v))
            for c, v in zip(measure_cols, row, strict=False)
        }
        for row in meas_arr
    ]
    props["isLocked"] = True  # match box path

    # GeoDataFrame with final columns
    gdf = gpd.GeoDataFrame(props, geometry=geom, crs=crs)

    # gdf.to_json keeps dict-like columns (classification/measurements) as JSON objects
    return json.loads(gdf.to_json(drop_id=True))


# --------------------------
# Unified builder (vectorized)
# --------------------------
def _build_geojson_dict_from_csv(
    csv: PathLike,
    *,
    overlap: float,
    results_dir: PathLike,
    output_dir: PathLike,
    prefix: str = "prob",
    object_type: str = "tile",
    set_classification: bool = False,
    annotation_shape: str = "box",  # "box" or "polygon"
    label_col: Optional[str] = None,
    # CSV read tuning
    usecols: Optional[List[str]] = None,
    dtype: Optional[Dict] = None,
) -> Tuple[PathLike, dict]:
    """Load a model-output CSV and build the GeoJSON dict plus destination.

    When ``annotation_shape='polygon'`` and a sibling ``<csv.stem>.h5`` exists
    under ``<results_dir>/patches/`` with a ``/polygons/{coords,offsets}``
    group, this delegates to :func:`_build_geojson_dict_from_h5` for the
    real cell contour; otherwise ``bbox`` is used as a fallback and a warning is
    emitted.  ``bbox`` mode goes through the original CSV path.

    Two classification modes are supported:

    * **Probability mode** (default, ``label_col=None``): looks for columns
      matching ``{prefix}_*`` (e.g. ``prob_0``, ``prob_1``, …) and classifies
      each feature by argmax over those soft scores.  This is the original
      path and is unchanged.

    * **Label mode** (``label_col`` is set, e.g. ``"niche_id"``): reads a
      single integer column as the direct class label.  Class names are derived
      as ``{prefix}_{label}`` (e.g. ``niche_0``, ``niche_1``, …).  The
      ``prefix_*`` column scan is skipped entirely, so there is no naming
      collision risk.  Use this for niche outputs where storing K one-hot
      columns per row would be wasteful.
    """
    # Always load the CSV first -- it is the source of truth for per-cell
    # probabilities / classification / center coords. The polygon group in
    # patches.h5 (when present) only carries cell contours (coords+offsets)
    # and no probability columns, so it must be merged onto the CSV by row
    # index.
    df = pd.read_csv(
        csv,
        usecols=usecols,
        dtype=dtype,
        engine="c",
        memory_map=True,
        low_memory=False,
    )

    if annotation_shape == "polygon":
        # Polygon mode: if patches.h5 has a /polygons group, synthesise a
        # 'polygon_wkt' column from it (by row index alignment). Missing
        # contours become NaN in 'polygon_wkt' and the polygon builder drops
        # them. Falls back to bbox when the group is entirely absent OR the
        # H5 decode fails -- in either case we MUST demote to 'box' below,
        # otherwise the dispatcher raises KeyError on a missing polygon_wkt.
        slide_stem = _to_local_path(csv).stem
        h5_path = _to_local_path(results_dir) / "patches" / f"{slide_stem}.h5"
        polygon_ok = False
        try:
            polygon_h5_exists = h5_path.exists()
            polygon_h5_has_group = polygon_h5_exists and _has_polygon_group(h5_path)
            if polygon_h5_has_group:
                wkts = _polygon_wkt_column_from_h5(h5_path, len(df))
                if wkts is not None:
                    df["polygon_wkt"] = wkts
                    n_kept = int(df["polygon_wkt"].notna().sum())
                    logger.info(
                        "annotation_shape='polygon': synthesised polygon_wkt from "
                        "%s for %d/%d rows.",
                        h5_path, n_kept, len(df),
                    )
                    if n_kept < len(df):
                        logger.warning(
                            "annotation_shape='polygon': %d CSV rows have no "
                            "matching H5 polygon (degenerate single-pixel cells).",
                            int((df['polygon_wkt'].isna()).sum()),
                        )
                    polygon_ok = True
                else:
                    logger.warning(
                        "annotation_shape='polygon': %s has /polygons group but "
                        "could not decode it; falling back to bbox path.",
                        h5_path,
                    )
            else:
                logger.warning(
                    "annotation_shape='polygon' requested but %s has no "
                    "/polygons group; falling back to bbox path.",
                    h5_path,
                )
        except Exception as _e:
            # Belt-and-braces: never let a malformed /polygons group propagate
            # out of the dispatcher. Fall back to bbox and continue.
            logger.warning(
                "annotation_shape='polygon': H5 decode via %s raised %s: %s; "
                "falling back to bbox path.",
                h5_path, type(_e).__name__, _e,
            )
        if not polygon_ok:
            # demote to box at the dispatcher so the right builder runs
            annotation_shape = "box"

    if label_col is not None:
        # ── Label mode ────────────────────────────────────────────────────────
        # Use a single integer column directly; skip prob_* column discovery.
        if label_col not in df.columns:
            raise KeyError(f"label_col '{label_col}' not found in {csv}")

        unique_labels = sorted(int(v) for v in df[label_col].dropna().unique())
        if not unique_labels:
            raise KeyError(f"No valid labels found in '{label_col}' column of {csv}")

        class_names = [f"{prefix}_{lab}" for lab in unique_labels]
        color_list = _make_distinct_colors(len(unique_labels))

        # Build a one-hot DataFrame so the existing box/polygon builders can
        # be reused without modification.  The expansion is in-memory only;
        # nothing is written back to the CSV file.
        id_vals = df[label_col].fillna(-1).astype(int)
        prob_cols = []
        for lab in unique_labels:
            oh_col = f"__oh_{lab}__"  # internal name, never exposed
            df[oh_col] = (id_vals == lab).astype(np.float32)
            prob_cols.append(oh_col)

    else:
        # ── Probability mode (original path, unchanged) ────────────────────
        prob_cols = [c for c in df.columns if c.startswith(f"{prefix}_")]
        if not prob_cols:
            raise KeyError(f"No {prefix}_* columns in {csv}")
        class_names = None  # builders derive names from prob_cols + prefix
        color_list = _make_distinct_colors(len(prob_cols))

    if annotation_shape == "box":
        geojson = _dataframe_to_geojson_box_fast(
            df,
            prob_cols,
            overlap,
            prefix=prefix,
            object_type=object_type,
            set_classification=set_classification,
            color_list=color_list,
            class_names=class_names,
        )
    else:
        # requires a 'polygon_wkt' column
        if "polygon_wkt" not in df.columns:
            raise KeyError(
                "polygon_wkt column is required for annotation_shape='polygon'"
            )
        geojson = _dataframe_to_geojson_polygon_fast(
            df,
            prob_cols,
            prefix=prefix,
            object_type=object_type,
            set_classification=set_classification,
            color_list=color_list,
            class_names=class_names,
        )

    out_path = results_dir / output_dir / f"{_to_local_path(csv).stem}.geojson"
    return out_path, geojson


# NOTE: With CLI flag --shape polygon (a71bbb9 + follow-ups) the H5 polygon path
#       is now the active code path when the polygon group is present in
#       patches.h5; otherwise csv_to_geojson() logs a warning and falls back to
#       bbox. The legacy `_build_geojson_dict_from_h5` kept below now reads from
#       /polygons/* and writes a FeatureCollection of True polygons.
def _has_polygon_group(h5_path: PathLike) -> bool:
    """Return True iff ``h5_path`` exists and contains ``/polygons/coords`` + ``/polygons/offsets``."""
    if not _to_local_path(h5_path).exists():
        return False
    try:
        with h5py.File(_to_local_path(h5_path), "r") as f:
            g = f.get("/polygons")
            if g is None:
                return False
            return ("coords" in g) and ("offsets" in g)
    except Exception:
        return False


def _polygon_wkt_column_from_h5(
    h5_path: Path,
    n_rows_expected: int,
) -> Optional[List[Optional[str]]]:
    """Decode /polygons/{coords,offsets} into a list of WKT strings.

    Reuses the same decoder embedded in `_build_geojson_dict_from_h5`.
    Returns one entry per cell; cells with fewer than 3 vertices (e.g.
    a 1-pixel degenerate instance) are returned as ``None`` so that the
    polygon builder in `_dataframe_to_geojson_polygon_fast` can skip
    them.

    The list is padded with ``None`` if the H5 polygon count is less than
    ``n_rows_expected`` (rare; usually a stitch dropped a polygon).

    Returns ``None`` if the H5 group is missing or unreadable, so the
    caller can decide on a fallback.
    """
    try:
        with _write_csv_to_h5_lock:
            with h5py.File(_to_local_path(h5_path), "r") as f:
                if "/polygons" not in f:
                    return None
                g = f["/polygons"]
                if "coords" not in g or "offsets" not in g:
                    return None
                coords = np.asarray(g["coords"])         # (K, 2) float32
                offsets = np.asarray(g["offsets"])       # (M+1,) int64
        if offsets.ndim != 1 or coords.ndim != 2 or coords.shape[1] != 2:
            return None
        n_h5 = int(len(offsets) - 1)
        n = max(n_h5, int(n_rows_expected))
        out: List[Optional[str]] = [None] * n
        for i in range(n_h5):
            s, e = int(offsets[i]), int(offsets[i + 1])
            xy = coords[s:e]  # (N_i, 2)
            if xy.size == 0 or xy.shape[0] < 3:
                out[i] = None  # degenerate; polygon builder will skip
                continue
            if not np.array_equal(xy[0], xy[-1]):
                xy = np.vstack([xy, xy[0]])
            ring = ", ".join(f"{float(x)} {float(y)}" for x, y in xy)
            out[i] = f"POLYGON (({ring}))"
        return out[: int(n_rows_expected)]
    except Exception:
        return None


def _build_geojson_dict_from_h5(
    h5_path: Path,
    *,
    overlap: float,
    results_dir: Path,
    output_dir: Path,
    prefix: str = "prob",
    object_type: str = "tile",
    set_classification: bool = False,
    annotation_shape: str = "polygon",   # HDF5 reader supports polygons (recommended)
    # no usecols/dtype knobs here; HDF5 datasets are already typed
) -> Tuple[Path, dict]:
    if annotation_shape != "polygon":
        raise NotImplementedError("HDF5 builder currently supports annotation_shape='polygon' only.")

    # ---- read geometry + per-polygon attributes ----
    with Lock:
        with h5py.File(h5_path, "r") as f:
            if "/polygons" not in f:
                raise KeyError("Group '/polygons' not found in HDF5.")

            g = f["/polygons"]

            if "coords" not in g or "offsets" not in g:
                raise KeyError("Expected datasets '/polygons/coords' and '/polygons/offsets'.")

            coords = np.asarray(g["coords"])         # (K, 2) float32
            offsets = np.asarray(g["offsets"])       # (M+1,) int64
            if offsets.ndim != 1 or coords.ndim != 2 or coords.shape[1] != 2:
                raise ValueError("Invalid shapes for coords/offsets in HDF5.")

            num_polys = int(len(offsets) - 1)

            # discover per-polygon probability datasets: {name: array(M,)}
            prob_cols: List[str] = []
            per_poly_data: Dict[str, np.ndarray] = {}
            for name, dset in g.items():
                if not isinstance(dset, h5py.Dataset):
                    continue
                if not name.startswith(f"{prefix}_"):
                    continue
                arr = np.asarray(dset)
                if arr.ndim == 1 and len(arr) == num_polys:
                    per_poly_data[name] = arr
                    prob_cols.append(name)

            if not prob_cols:
                raise KeyError(f"No per-polygon datasets starting with '{prefix}_' in {h5_path}")

            # ---- reconstruct polygons into WKT ----
            def poly_wkt(i: int) -> str:
                s, e = int(offsets[i]), int(offsets[i + 1])
                xy = coords[s:e]  # (N_i, 2)
                if xy.size == 0:
                    # represent an empty polygon as an empty ring (rare)
                    return "POLYGON EMPTY"
                # Ensure closed ring (repeat first point if needed)
                if not np.array_equal(xy[0], xy[-1]):
                    xy = np.vstack([xy, xy[0]])
                # WKT uses "x y" pairs
                ring = ", ".join(f"{float(x)} {float(y)}" for x, y in xy)
                return f"POLYGON (({ring}))"

            polygon_wkts = [poly_wkt(i) for i in range(num_polys)]

    # ---- build a DataFrame that matches your *_to_geojson_polygon_fast() input ----
    data = {"polygon_wkt": polygon_wkts}
    for k, v in per_poly_data.items():
        data[k] = v
    df = pd.DataFrame(data)

    # colors based on discovered probability columns
    color_list = _make_distinct_colors(len(prob_cols))

    # ---- delegate to your existing fast converter ----
    geojson = _dataframe_to_geojson_polygon_fast(
        df,
        prob_cols,
        prefix=prefix,
        object_type=object_type,
        set_classification=set_classification,
        color_list=color_list,
    )

    out_path = results_dir / output_dir / f"{h5_path.stem}.geojson"
    return out_path, geojson


# --------------------------
# Writer (atomic rename)
# --------------------------
def _is_uri_path(obj: object) -> bool:
    """Return True when `obj` is already a `URIPath` instance."""
    return isinstance(obj, URIPath)


def _iter_files(path: PathLike, *, suffix: Optional[str] = None):
    """Iterate over files below `path`, honoring both local and URI paths."""
    if isinstance(path, URIPath):
        iterator = path.iterdir(files_only=True)
    else:
        iterator = (child for child in path.iterdir() if child.is_file())
    for child in iterator:
        if suffix is None or child.suffix == suffix:
            yield child


def _write_geojson_bytes(
    out_path: PathLike, payload: bytes, atomic: bool = True
) -> None:
    """Write GeoJSON bytes, optionally via atomic rename for local paths."""
    parent = out_path.parent
    parent.mkdir(parents=True, exist_ok=True)

    if isinstance(out_path, URIPath):
        # Remote paths rely on URIPath to sync caches back to the backend.
        with out_path.open("wb") as f:
            f.write(payload)
        return

    if atomic:
        tmp = out_path.with_suffix(out_path.suffix + ".PART")
        with open(tmp, "wb", buffering=1 << 20) as f:
            f.write(payload)
        tmp.replace(out_path)
    else:
        with open(out_path, "wb", buffering=1 << 20) as f:
            f.write(payload)


def _worker(
    csv,
    overlap,
    results_dir,
    output_dir,
    prefix,
    object_type,
    set_classification,
    annotation_shape,
    label_col,
    usecols,
    dtype,
    atomic_writes,
):
    """Process a single CSV in a worker process and persist the GeoJSON."""
    # Build + encode (serial)
    out_path, geojson = _build_geojson_dict_from_csv(
        csv,
        overlap=overlap,
        results_dir=results_dir,
        output_dir=output_dir,
        prefix=prefix,
        object_type=object_type,
        set_classification=set_classification,
        annotation_shape=annotation_shape,
        label_col=label_col,
        usecols=usecols,
        dtype=dtype,
    )

    payload = _dumps(geojson)

    # Write (atomic)
    _write_geojson_bytes(out_path, payload, atomic=atomic_writes)


def write_geojsons(
    csvs: List[PathLike],
    *,
    results_dir: PathLike,
    overlap: float,
    # input_dir: Path = Path("."),
    output_dir: Path = Path("."),
    prefix: str = "prob",
    num_workers=8,
    object_type: str = "tile",
    set_classification: bool = False,
    annotation_shape: str = "box",  # "box" or "polygon"
    label_col: Optional[str] = None,
    atomic_writes: bool = True,
    overwrite: bool = False,
    usecols: Optional[
        List[str]
    ] = None,  # e.g., ["minx","miny","width","height", "polygon_wkt", *prob_cols]
    dtype: Optional[Dict] = None,  # e.g., {"minx":"int32", ...}
    show_progress: bool = True,
    print_timings: bool = False,
) -> None:
    """Convert CSV outputs to GeoJSON concurrently and store results."""
    # Basic validations
    if not results_dir.exists():
        raise FileNotFoundError(f"results_dir does not exist: {results_dir}")

    missing_dirs = sorted(
        {p.parent for p in csvs if not p.parent.exists()}, key=lambda x: str(x)
    )
    if missing_dirs:
        missing_str = ", ".join(str(d) for d in missing_dirs)
        raise FileNotFoundError(
            "GeoJSON input CSV directory not found: " f"{missing_str}"
        )

    out_root = results_dir / output_dir
    out_root.mkdir(parents=True, exist_ok=True)

    # Skip those already done (unless overwrite requested)
    if overwrite:
        already = set()
    else:
        already = {p.stem for p in _iter_files(out_root, suffix=".geojson")}
    csvs = [p for p in csvs if p.stem not in already]
    total = len(csvs)
    if total == 0:
        if print_timings:
            print("No new CSVs to process.")
        return

    pbar = (
        tqdm(total=total, desc="Files completed", dynamic_ncols=True)
        if show_progress
        else None
    )

    # Run with progress bar
    with ProcessPoolExecutor(max_workers=num_workers) as ex:
        futures = [
            ex.submit(
                _worker,
                args,
                overlap,
                results_dir,
                output_dir,
                prefix,
                object_type,
                set_classification,
                annotation_shape,
                label_col,
                usecols,
                dtype,
                atomic_writes,
            )
            for args in csvs
        ]

        # pbar = tqdm(total=len(futures)) if pbar is None else pbar
        for f in cancellable_as_completed(futures, ex):
            # throttle_when_busy(target_util=0.9)
            f.result()
            if pbar:
                pbar.update(1)

    if pbar:
        pbar.close()
