"""High-throughput conversion of model-output CSVs into GeoJSON overlays."""

# geojson_vectorized_serial.py
from __future__ import annotations

import logging
import threading as _threading
import uuid
from colorsys import hsv_to_rgb

# from shapely.geometry import Polygon, MultiPolygon  # (imported only for typing)
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
from typing import Dict
from typing import List
from typing import Optional
from typing import Tuple
from typing import Union

import h5py
import numpy as np
import orjson
import pandas as pd
import shapely
from shapely import from_wkt  # shapely >= 2.0
from tqdm.auto import tqdm

from .cli.export import _to_local_path  # local URI-vs-Path resolver

logger = logging.getLogger(__name__)
_write_csv_to_h5_lock = _threading.Lock()
# `Lock` is referenced by the legacy (dead) `_build_geojson_dict_from_h5`
# below; keep an alias so it cannot NameError if anything ever calls it.
Lock = _write_csv_to_h5_lock

from .cancel import cancellable_as_completed
from .uri_path import URIPath

PathLike = Union[Path, URIPath]

# Columns that carry geometry/identity — excluded from per-cell measurements.
_GEOM_COLS = frozenset(
    {
        "minx",
        "miny",
        "width",
        "height",
        "center_x",
        "center_y",
        "polygon_wkt",
    }
)

# from .num_worker_optimizer import pick_workers_safe, throttle_when_busy

# ---- fast JSON encoder ----


def _dumps(obj) -> bytes:
    """Serialize a GeoJSON payload; already-encoded bytes pass straight through."""
    if isinstance(obj, (bytes, bytearray)):
        return bytes(obj)
    return orjson.dumps(obj, option=orjson.OPT_SERIALIZE_NUMPY)


# --------------------------
# Helpers
# --------------------------
def _make_distinct_colors(
    n: int,
    s: float = 0.70,
    v: float = 0.90,
    shuffle: bool = True,
    seed: Optional[int] = None,
):
    """Return `n` well-spaced HSV-derived colors for class visualization."""
    if n <= 0:
        raise ValueError("n must be > 0")
    hues = [i / n for i in range(n)]
    if shuffle and n > 2:
        order, L, R = [], 0, n - 1
        while L <= R:
            order.append(L)
            if L != R:
                order.append(R)
            L += 1
            R -= 1
        hues = [hues[i] for i in order]
    if seed is not None:
        import random

        random.seed(seed)

    out = []
    for h in hues:
        r, g, b = hsv_to_rgb(h, s, v)
        R, G, B = (int(round(r * 255)), int(round(g * 255)), int(round(b * 255)))
        out.append(
            {"hex": f"#{R:02X}{G:02X}{B:02X}", "rgb": (R, G, B), "hsv": (h, s, v)}
        )
    return out


# --------------------------
# BOX path (vectorized)
# --------------------------
def _dataframe_to_geojson_box_fast(
    df: pd.DataFrame,
    prob_cols: List[str],
    overlap: float,
    *,
    prefix: str = "prob",
    object_type: str = "tile",
    set_classification: bool = False,
    color_list: Optional[List[dict]] = None,
    class_names: Optional[List[str]] = None,
) -> dict:
    """Vectorize CSV tile boxes into a GeoJSON FeatureCollection."""
    # Keep only valid rows for probs
    df = df.dropna(subset=[c for c in prob_cols if c.startswith(prefix)])

    # Pull numeric columns to arrays (no per-row pandas calls)
    xywh = df[["minx", "miny", "width", "height"]].to_numpy(dtype=np.int64, copy=False)
    minx, miny, w, h = xywh.T

    # Vectorized patch math
    pw = np.rint(w * (1.0 - overlap)).astype(np.int64)
    ph = np.rint(h * (1.0 - overlap)).astype(np.int64)
    pmx = np.rint((w - pw) * 0.5).astype(np.int64)
    pmy = np.rint((h - ph) * 0.5).astype(np.int64)

    minx2 = minx + pmx
    miny2 = miny + pmy
    maxx2 = minx2 + pw
    maxy2 = miny2 + ph

    # Closed ring coordinates (N, 5, 2)
    coords = np.stack(
        [
            np.stack([maxx2, miny2], axis=1),
            np.stack([maxx2, maxy2], axis=1),
            np.stack([minx2, maxy2], axis=1),
            np.stack([minx2, miny2], axis=1),
            np.stack([maxx2, miny2], axis=1),
        ],
        axis=1,
    )

    # Probs as matrix, argmax vectorized (classification only)
    probs = df[prob_cols].to_numpy(dtype=np.float32, copy=False)
    arg = probs.argmax(axis=1)

    if color_list is None:
        color_list = _make_distinct_colors(len(prob_cols))

    if class_names is None:
        class_names = [
            f"{prefix}_{c[len(prefix) + 1:]}"
            if c.startswith(f"{prefix}_")
            else f"{prefix}_{c}"
            for c in prob_cols
        ]

    # All numeric non-geometry columns → measurements (includes prob_*, hplot_*, ncomp_*, etc.)
    # Exclude internal __oh_*__ one-hot columns generated by the label_col path.
    measure_cols = [
        c
        for c in df.columns
        if c not in _GEOM_COLS
        and not c.startswith("__oh_")
        and pd.api.types.is_numeric_dtype(df[c])
    ]
    meas_arr = df[measure_cols].to_numpy(dtype=np.float64, copy=False)

    # Build features in one tight Python loop (no pandas ops inside)
    features = []
    for i in range(len(df)):
        measurements = {
            c: (None if np.isnan(v) else float(v))
            for c, v in zip(measure_cols, meas_arr[i], strict=False)
        }
        feat = {
            "type": "Feature",
            "id": str(uuid.uuid4()),
            # "geometry": {"type": "Polygon", "coordinates": [list(map(tuple, coords[i]))]},
            "geometry": {"type": "Polygon", "coordinates": [coords[i].tolist()]},
            "properties": {
                "isLocked": True,
                "measurements": measurements,
                "objectType": object_type,
            },
        }
        if set_classification:
            ci = int(arg[i])
            feat["properties"]["classification"] = {
                "name": class_names[ci],
                "color": list(color_list[ci]["rgb"]),
            }
        features.append(feat)

    return {"type": "FeatureCollection", "features": features}


# --------------------------
# POLYGON/WKT path (GeoPandas + Shapely vectorized)
# --------------------------
def _sanitize_polygon_rings(
    df: pd.DataFrame,
    geom: np.ndarray,
) -> Tuple[np.ndarray, int, int]:
    """Repair rings so every feature is a strictly valid polygon.

    JTS-based GeoJSON consumers (e.g. QuPath) run
    ``GeometryPrecisionReducer`` on import, which raises
    ``IllegalArgumentException: Reduction failed, possible invalid input``
    for self-touching rings -- cv2.findContours emits these for cells with
    a 1-pixel neck, where the contour revisits a vertex ("pinch" contour).
    GEOS' ``make_valid`` repairs such geometry and is a semantic no-op on
    already-valid rings.

    Rows that still do not resolve to a polygon -- a null WKT (degenerate
    single-pixel cell with no stored contour) or a contour that collapses
    to zero area -- fall back to their bbox rectangle
    (``minx``/``miny``/``width``/``height``) so no cell is dropped.

    Returns ``(geometries, n_repaired, n_boxed)``.  When nothing is
    invalid the original ``geom`` array is returned unmodified.
    """
    # is_valid() -> False for null AND for self-touching rings
    bad = np.flatnonzero(~shapely.is_valid(geom))
    if bad.size == 0:
        return geom, 0, 0

    wkb = shapely.to_wkb(geom)  # nulls -> b""; only the bad rows are touched
    fixed_wkb = wkb.copy()
    have_bbox = all(c in df.columns for c in ("minx", "miny", "width", "height"))
    minx = miny = w = h = None
    if have_bbox:
        minx, miny, w, h = (
            df[["minx", "miny", "width", "height"]]
            .to_numpy(dtype=np.float64, copy=False)
            .T
        )
    n_repaired = 0
    n_boxed = 0
    for i in bad:
        g = shapely.from_wkb(wkb[i])
        replacement = None
        if g is not None:
            try:
                fixed = shapely.make_valid(g)
            except Exception:
                fixed = None
            if fixed is not None and not fixed.is_empty:
                if fixed.geom_type in ("MultiPolygon", "GeometryCollection"):
                    k = int(shapely.get_num_geometries(fixed))
                    parts = [shapely.get_geometry(fixed, j) for j in range(k)]
                else:
                    parts = [fixed]
                polys = [
                    p
                    for p in parts
                    if p is not None and p.geom_type == "Polygon" and not p.is_empty
                ]
                # keep the dominant lobe; a pinch splits the cell at the neck
                if polys:
                    replacement = max(polys, key=lambda p: p.area)
        if replacement is None:
            if not have_bbox:
                continue  # legacy behaviour: leave the geometry null
            if not all(np.isfinite(v) for v in (minx[i], miny[i], w[i], h[i])):
                continue
            bw = max(float(w[i]), 1.0)
            bh = max(float(h[i]), 1.0)
            replacement = shapely.box(minx[i], miny[i], minx[i] + bw, miny[i] + bh)
            n_boxed += 1
        else:
            n_repaired += 1
        fixed_wkb[i] = shapely.to_wkb(replacement)
    return shapely.from_wkb(fixed_wkb), n_repaired, n_boxed


def _dataframe_to_geojson_polygon_fast(
    df: pd.DataFrame,
    prob_cols: List[str],
    *,
    prefix: str = "prob",
    object_type: str = "tile",
    set_classification: bool = False,
    color_list: Optional[List[dict]] = None,
    class_names: Optional[List[str]] = None,
    crs: Optional[str] = None,
) -> dict:
    """Convert WKT-backed polygon annotations into a GeoJSON dict."""
    geom = from_wkt(df["polygon_wkt"])
    return orjson.loads(
        _polygon_geojson_bytes(
            df.drop(columns=["polygon_wkt"]),
            geom,
            prob_cols,
            prefix=prefix,
            object_type=object_type,
            set_classification=set_classification,
            color_list=color_list,
            class_names=class_names,
        )
    )


def _polygon_geojson_bytes(
    props: pd.DataFrame,
    geom: np.ndarray,
    prob_cols: List[str],
    *,
    prefix: str = "prob",
    object_type: str = "tile",
    set_classification: bool = False,
    color_list: Optional[List[dict]] = None,
    class_names: Optional[List[str]] = None,
) -> bytes:
    """Serialize polygons plus per-cell properties straight to GeoJSON bytes.

    The FeatureCollection is never materialised as a Python dict.
    ``shapely.to_geojson`` is a ufunc, so contour vertices stay inside GEOS
    instead of becoming nested lists -- that round-trip is what made
    ``GeoDataFrame.to_json`` dominate the export.
    """
    # Repair self-touching rings (JTS importers, e.g. QuPath, crash on them)
    # and demote null/degenerate rows to their bbox rectangle.
    geom, n_repaired, n_boxed = _sanitize_polygon_rings(props, geom)
    if n_repaired or n_boxed:
        logger.info(
            "annotation_shape='polygon': repaired %d self-touching ring(s) "
            "and wrote %d degenerate cell(s) as bbox rectangle(s).",
            n_repaired,
            n_boxed,
        )

    probs = props[prob_cols].to_numpy(dtype=np.float32, copy=False)
    idx = probs.argmax(axis=1)

    if class_names is None:
        class_names = [
            f"{prefix}_{c[len(prefix) + 1:]}"
            if c.startswith(f"{prefix}_")
            else f"{prefix}_{c}"
            for c in prob_cols
        ]
    if color_list is None:
        color_list = _make_distinct_colors(len(prob_cols))

    # All numeric non-geometry columns -> measurements (includes prob_*,
    # hplot_*, ncomp_*, ...).  Exclude internal __oh_*__ one-hot columns.
    measure_cols = [
        c
        for c in props.columns
        if c not in _GEOM_COLS
        and not c.startswith("__oh_")
        and pd.api.types.is_numeric_dtype(props[c])
    ]
    meas_arr = props[measure_cols].to_numpy(dtype=np.float64, copy=False)

    # Plain arrays so the per-row record build never re-enters pandas.
    col_names = [c for c in props.columns if not c.startswith("__oh_")]
    col_arrays = [props[c].to_numpy() for c in col_names]

    geom_json = shapely.to_geojson(geom)

    opt = orjson.OPT_SERIALIZE_NUMPY
    parts: List[bytes] = [b'{"type":"FeatureCollection","features":[']
    sep = b""
    for i in range(len(props)):
        record = {c: a[i] for c, a in zip(col_names, col_arrays, strict=False)}
        record["objectType"] = object_type
        if set_classification:
            ci = int(idx[i])
            record["classification"] = {
                "name": class_names[ci],
                "color": list(color_list[ci]["rgb"]),
            }
        record["measurements"] = {
            c: (None if np.isnan(v) else float(v))
            for c, v in zip(measure_cols, meas_arr[i], strict=False)
        }
        record["isLocked"] = True

        gj = geom_json[i]
        parts.append(sep)
        parts.append(b'{"type":"Feature","geometry":')
        parts.append(b"null" if gj is None else gj.encode())
        parts.append(b',"properties":')
        parts.append(orjson.dumps(record, option=opt))
        parts.append(b"}")
        sep = b","
    parts.append(b"]}")
    return b"".join(parts)


# --------------------------
# Unified builder (vectorized)
# --------------------------
def _build_geojson_dict_from_csv(
    csv: PathLike,
    *,
    overlap: float,
    results_dir: PathLike,
    output_dir: PathLike,
    prefix: str = "prob",
    object_type: str = "tile",
    set_classification: bool = False,
    annotation_shape: str = "bbox",  # "bbox" or "polygon"
    label_col: Optional[str] = None,
    # CSV read tuning
    usecols: Optional[List[str]] = None,
    dtype: Optional[Dict] = None,
) -> Tuple[PathLike, dict]:
    """Load a model-output CSV and build the GeoJSON dict plus destination.

    When ``annotation_shape='polygon'`` and a sibling ``<csv.stem>.h5`` exists
    under ``<results_dir>/patches/`` with a ``/polygons/{coords,offsets}``
    group, the real cell contour is read from it; otherwise ``bbox`` is used
    as a fallback and a warning is emitted.  Individual rows without a
    contour (degenerate single-pixel cells) are written as their bbox
    rectangle rather than dropped.  ``bbox`` mode goes through the
    original CSV path.

    Two classification modes are supported:

    * **Probability mode** (default, ``label_col=None``): looks for columns
      matching ``{prefix}_*`` (e.g. ``prob_0``, ``prob_1``, …) and classifies
      each feature by argmax over those soft scores.  This is the original
      path and is unchanged.

    * **Label mode** (``label_col`` is set, e.g. ``"niche_id"``): reads a
      single integer column as the direct class label.  Class names are derived
      as ``{prefix}_{label}`` (e.g. ``niche_0``, ``niche_1``, …).  The
      ``prefix_*`` column scan is skipped entirely, so there is no naming
      collision risk.  Use this for niche outputs where storing K one-hot
      columns per row would be wasteful.
    """
    # Always load the CSV first -- it is the source of truth for per-cell
    # probabilities / classification / center coords. The polygon group in
    # patches.h5 (when present) only carries cell contours (coords+offsets)
    # and no probability columns, so it must be merged onto the CSV by row
    # index.
    df = pd.read_csv(
        csv,
        usecols=usecols,
        dtype=dtype,
        engine="c",
        memory_map=True,
        low_memory=False,
    )

    # Bound for every shape, so an unexpected value cannot raise UnboundLocalError.
    polygon_geom = None

    if annotation_shape == "polygon":
        # Polygon mode: if patches.h5 has a /polygons group, decode it straight
        # into a Shapely geometry array (aligned by row index). Cells without a
        # usable contour stay None and are demoted to their bbox rectangle by
        # the builder. Falls back to bbox when the group is absent OR the decode
        # fails -- in either case we MUST demote to 'box' below.
        slide_stem = _to_local_path(csv).stem
        h5_path = _to_local_path(results_dir) / "patches" / f"{slide_stem}.h5"
        polygon_ok = False
        try:
            polygon_h5_exists = h5_path.exists()
            polygon_h5_has_group = polygon_h5_exists and _has_polygon_group(h5_path)
            if polygon_h5_has_group:
                polygon_geom = _polygons_from_h5(h5_path, len(df))
                if polygon_geom is not None:
                    n_missing = int(sum(g is None for g in polygon_geom))
                    logger.info(
                        "annotation_shape='polygon': decoded polygons from "
                        "%s for %d/%d rows.",
                        h5_path,
                        len(df) - n_missing,
                        len(df),
                    )
                    if n_missing:
                        logger.warning(
                            "annotation_shape='polygon': %d CSV rows have no "
                            "matching H5 polygon (degenerate single-pixel cells); "
                            "they are written as bbox rectangles.",
                            n_missing,
                        )
                    polygon_ok = True
                else:
                    logger.warning(
                        "annotation_shape='polygon': %s has /polygons group but "
                        "could not decode it; falling back to bbox path.",
                        h5_path,
                    )
            else:
                logger.warning(
                    "annotation_shape='polygon' requested but %s has no "
                    "/polygons group; falling back to bbox path.",
                    h5_path,
                )
        except Exception as _e:
            # Belt-and-braces: never let a malformed /polygons group propagate
            # out of the dispatcher. Fall back to bbox and continue.
            logger.warning(
                "annotation_shape='polygon': H5 decode via %s raised %s: %s; "
                "falling back to bbox path.",
                h5_path,
                type(_e).__name__,
                _e,
            )
        if not polygon_ok:
            # demote to bbox at the dispatcher so the right builder runs
            annotation_shape = "bbox"

    if label_col is not None:
        # ── Label mode ────────────────────────────────────────────────────────
        # Use a single integer column directly; skip prob_* column discovery.
        if label_col not in df.columns:
            raise KeyError(f"label_col '{label_col}' not found in {csv}")

        unique_labels = sorted(int(v) for v in df[label_col].dropna().unique())
        if not unique_labels:
            raise KeyError(f"No valid labels found in '{label_col}' column of {csv}")

        class_names = [f"{prefix}_{lab}" for lab in unique_labels]
        color_list = _make_distinct_colors(len(unique_labels))

        # Build a one-hot DataFrame so the existing box/polygon builders can
        # be reused without modification.  The expansion is in-memory only;
        # nothing is written back to the CSV file.
        id_vals = df[label_col].fillna(-1).astype(int)
        prob_cols = []
        for lab in unique_labels:
            oh_col = f"__oh_{lab}__"  # internal name, never exposed
            df[oh_col] = (id_vals == lab).astype(np.float32)
            prob_cols.append(oh_col)

    else:
        # ── Probability mode (original path, unchanged) ────────────────────
        prob_cols = [c for c in df.columns if c.startswith(f"{prefix}_")]
        if not prob_cols:
            raise KeyError(f"No {prefix}_* columns in {csv}")
        class_names = None  # builders derive names from prob_cols + prefix
        color_list = _make_distinct_colors(len(prob_cols))

    if annotation_shape == "bbox":
        geojson = _dataframe_to_geojson_box_fast(
            df,
            prob_cols,
            overlap,
            prefix=prefix,
            object_type=object_type,
            set_classification=set_classification,
            color_list=color_list,
            class_names=class_names,
        )
    elif annotation_shape == "polygon":
        if polygon_geom is None:
            raise KeyError(
                "polygon geometries are required for annotation_shape='polygon'"
            )
        geojson = _polygon_geojson_bytes(
            df,
            polygon_geom,
            prob_cols,
            prefix=prefix,
            object_type=object_type,
            set_classification=set_classification,
            color_list=color_list,
            class_names=class_names,
        )
    else:
        raise ValueError(
            "annotation_shape must be 'bbox' or 'polygon', " f"got {annotation_shape!r}"
        )

    out_path = results_dir / output_dir / f"{_to_local_path(csv).stem}.geojson"
    return out_path, geojson


# NOTE: With CLI flag --shape polygon (a71bbb9 + follow-ups) the H5 polygon path
#       is now the active code path when the polygon group is present in
#       patches.h5; otherwise csv_to_geojson() logs a warning and falls back to
#       bbox. The legacy `_build_geojson_dict_from_h5` kept below now reads from
#       /polygons/* and writes a FeatureCollection of True polygons.
def _has_polygon_group(h5_path: PathLike) -> bool:
    """Return True iff ``h5_path`` exists and contains ``/polygons/coords`` + ``/polygons/offsets``."""
    if not _to_local_path(h5_path).exists():
        return False
    try:
        with h5py.File(_to_local_path(h5_path), "r") as f:
            g = f.get("/polygons")
            if g is None:
                return False
            return ("coords" in g) and ("offsets" in g)
    except Exception:
        return False


def _polygons_from_h5(
    h5_path: PathLike,
    n_rows_expected: int,
) -> Optional[np.ndarray]:
    """Build a Shapely geometry array straight from ``/polygons/{coords,offsets}``.

    ``linearrings``/``polygons`` are Shapely 2 ufuncs that consume the flat
    coordinate buffer directly, so the WKT round-trip this replaces (one
    f-string per contour, then ``from_wkt`` to parse them all back) is skipped.

    Cells whose contour cannot form a ring stay ``None`` so
    :func:`_sanitize_polygon_rings` can demote them to their bbox rectangle.
    Returns ``None`` when the group is missing or unreadable, so the caller can
    fall back to the box path.
    """
    try:
        with _write_csv_to_h5_lock:
            with h5py.File(_to_local_path(h5_path), "r") as f:
                g = f.get("/polygons")
                if g is None or "coords" not in g or "offsets" not in g:
                    return None
                coords = np.asarray(g["coords"])  # (K, 2)
                offsets = np.asarray(g["offsets"])  # (M+1,)
        if offsets.ndim != 1 or coords.ndim != 2 or coords.shape[1] != 2:
            return None

        n = int(n_rows_expected)
        n_h5 = int(len(offsets) - 1)
        if n_h5 <= 0 or coords.size == 0:
            return np.full(n, None, dtype=object)

        counts = np.diff(offsets).astype(np.int64)
        first = coords[offsets[:-1]]
        last = coords[offsets[1:] - 1]
        # A ring that already repeats its first vertex spends one point on the
        # closure, so it needs a 4th to still describe a triangle.
        closed = np.all(first == last, axis=1) & (counts > 0)
        ok = counts >= np.where(closed, 4, 3)

        geom = np.full(n_h5, None, dtype=object)
        if ok.any():
            rings = shapely.linearrings(
                coords[np.repeat(ok, counts)].astype(np.float64),
                indices=np.repeat(np.arange(int(ok.sum())), counts[ok]),
            )
            geom[ok] = shapely.polygons(rings)

        if n_h5 >= n:
            return geom[:n]
        out = np.full(n, None, dtype=object)
        out[:n_h5] = geom
        return out
    except Exception:
        return None


def _build_geojson_dict_from_h5(
    h5_path: Path,
    *,
    overlap: float,
    results_dir: Path,
    output_dir: Path,
    prefix: str = "prob",
    object_type: str = "tile",
    set_classification: bool = False,
    annotation_shape: str = "polygon",  # HDF5 reader supports polygons (recommended)
    # no usecols/dtype knobs here; HDF5 datasets are already typed
) -> Tuple[Path, dict]:
    if annotation_shape != "polygon":
        raise NotImplementedError(
            "HDF5 builder currently supports annotation_shape='polygon' only."
        )

    # ---- read geometry + per-polygon attributes ----
    with Lock:
        with h5py.File(h5_path, "r") as f:
            if "/polygons" not in f:
                raise KeyError("Group '/polygons' not found in HDF5.")

            g = f["/polygons"]

            if "coords" not in g or "offsets" not in g:
                raise KeyError(
                    "Expected datasets '/polygons/coords' and '/polygons/offsets'."
                )

            coords = np.asarray(g["coords"])  # (K, 2) float32
            offsets = np.asarray(g["offsets"])  # (M+1,) int64
            if offsets.ndim != 1 or coords.ndim != 2 or coords.shape[1] != 2:
                raise ValueError("Invalid shapes for coords/offsets in HDF5.")

            num_polys = int(len(offsets) - 1)

            # discover per-polygon probability datasets: {name: array(M,)}
            prob_cols: List[str] = []
            per_poly_data: Dict[str, np.ndarray] = {}
            for name, dset in g.items():
                if not isinstance(dset, h5py.Dataset):
                    continue
                if not name.startswith(f"{prefix}_"):
                    continue
                arr = np.asarray(dset)
                if arr.ndim == 1 and len(arr) == num_polys:
                    per_poly_data[name] = arr
                    prob_cols.append(name)

            if not prob_cols:
                raise KeyError(
                    f"No per-polygon datasets starting with '{prefix}_' in {h5_path}"
                )

            # ---- reconstruct polygons into WKT ----
            def poly_wkt(i: int) -> str:
                s, e = int(offsets[i]), int(offsets[i + 1])
                xy = coords[s:e]  # (N_i, 2)
                if xy.size == 0:
                    # represent an empty polygon as an empty ring (rare)
                    return "POLYGON EMPTY"
                # Ensure closed ring (repeat first point if needed)
                if not np.array_equal(xy[0], xy[-1]):
                    xy = np.vstack([xy, xy[0]])
                # WKT uses "x y" pairs
                ring = ", ".join(f"{float(x)} {float(y)}" for x, y in xy)
                return f"POLYGON (({ring}))"

            polygon_wkts = [poly_wkt(i) for i in range(num_polys)]

    # ---- build a DataFrame that matches your *_to_geojson_polygon_fast() input ----
    data = {"polygon_wkt": polygon_wkts}
    for k, v in per_poly_data.items():
        data[k] = v
    df = pd.DataFrame(data)

    # colors based on discovered probability columns
    color_list = _make_distinct_colors(len(prob_cols))

    # ---- delegate to your existing fast converter ----
    geojson = _dataframe_to_geojson_polygon_fast(
        df,
        prob_cols,
        prefix=prefix,
        object_type=object_type,
        set_classification=set_classification,
        color_list=color_list,
    )

    out_path = results_dir / output_dir / f"{h5_path.stem}.geojson"
    return out_path, geojson


# --------------------------
# Writer (atomic rename)
# --------------------------
def _is_uri_path(obj: object) -> bool:
    """Return True when `obj` is already a `URIPath` instance."""
    return isinstance(obj, URIPath)


def _iter_files(path: PathLike, *, suffix: Optional[str] = None):
    """Iterate over files below `path`, honoring both local and URI paths."""
    if isinstance(path, URIPath):
        iterator = path.iterdir(files_only=True)
    else:
        iterator = (child for child in path.iterdir() if child.is_file())
    for child in iterator:
        if suffix is None or child.suffix == suffix:
            yield child


def _write_geojson_bytes(
    out_path: PathLike, payload: bytes, atomic: bool = True
) -> None:
    """Write GeoJSON bytes, optionally via atomic rename for local paths."""
    parent = out_path.parent
    parent.mkdir(parents=True, exist_ok=True)

    if isinstance(out_path, URIPath):
        # Remote paths rely on URIPath to sync caches back to the backend.
        with out_path.open("wb") as f:
            f.write(payload)
        return

    if atomic:
        tmp = out_path.with_suffix(out_path.suffix + ".PART")
        with open(tmp, "wb", buffering=1 << 20) as f:
            f.write(payload)
        tmp.replace(out_path)
    else:
        with open(out_path, "wb", buffering=1 << 20) as f:
            f.write(payload)


def _worker(
    csv,
    overlap,
    results_dir,
    output_dir,
    prefix,
    object_type,
    set_classification,
    annotation_shape,
    label_col,
    usecols,
    dtype,
    atomic_writes,
):
    """Process a single CSV in a worker process and persist the GeoJSON."""
    # Build + encode (serial)
    out_path, geojson = _build_geojson_dict_from_csv(
        csv,
        overlap=overlap,
        results_dir=results_dir,
        output_dir=output_dir,
        prefix=prefix,
        object_type=object_type,
        set_classification=set_classification,
        annotation_shape=annotation_shape,
        label_col=label_col,
        usecols=usecols,
        dtype=dtype,
    )

    payload = _dumps(geojson)

    # Write (atomic)
    _write_geojson_bytes(out_path, payload, atomic=atomic_writes)


def write_geojsons(
    csvs: List[PathLike],
    *,
    results_dir: PathLike,
    overlap: float,
    # input_dir: Path = Path("."),
    output_dir: Path = Path("."),
    prefix: str = "prob",
    num_workers=8,
    object_type: str = "tile",
    set_classification: bool = False,
    annotation_shape: str = "bbox",  # "bbox" or "polygon"
    label_col: Optional[str] = None,
    atomic_writes: bool = True,
    overwrite: bool = False,
    usecols: Optional[
        List[str]
    ] = None,  # e.g., ["minx","miny","width","height", "polygon_wkt", *prob_cols]
    dtype: Optional[Dict] = None,  # e.g., {"minx":"int32", ...}
    show_progress: bool = True,
    print_timings: bool = False,
) -> None:
    """Convert CSV outputs to GeoJSON concurrently and store results."""
    # Basic validations
    if not results_dir.exists():
        raise FileNotFoundError(f"results_dir does not exist: {results_dir}")

    missing_dirs = sorted(
        {p.parent for p in csvs if not p.parent.exists()}, key=lambda x: str(x)
    )
    if missing_dirs:
        missing_str = ", ".join(str(d) for d in missing_dirs)
        raise FileNotFoundError(
            "GeoJSON input CSV directory not found: " f"{missing_str}"
        )

    out_root = results_dir / output_dir
    out_root.mkdir(parents=True, exist_ok=True)

    # Skip those already done (unless overwrite requested)
    if overwrite:
        already = set()
    else:
        already = {p.stem for p in _iter_files(out_root, suffix=".geojson")}
    csvs = [p for p in csvs if p.stem not in already]
    total = len(csvs)
    if total == 0:
        if print_timings:
            print("No new CSVs to process.")
        return

    pbar = (
        tqdm(total=total, desc="Files completed", dynamic_ncols=True)
        if show_progress
        else None
    )

    # Run with progress bar
    with ProcessPoolExecutor(max_workers=num_workers) as ex:
        futures = [
            ex.submit(
                _worker,
                args,
                overlap,
                results_dir,
                output_dir,
                prefix,
                object_type,
                set_classification,
                annotation_shape,
                label_col,
                usecols,
                dtype,
                atomic_writes,
            )
            for args in csvs
        ]

        # pbar = tqdm(total=len(futures)) if pbar is None else pbar
        for f in cancellable_as_completed(futures, ex):
            # throttle_when_busy(target_util=0.9)
            f.result()
            if pbar:
                pbar.update(1)

    if pbar:
        pbar.close()
